# Generated by Django 3.2.4 on 2022-11-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_uploadimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimages',
            name='image',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
