# Generated by Django 3.2.4 on 2022-11-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_uploadimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimages',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/images'),
        ),
    ]
