# Generated by Django 3.2.4 on 2022-11-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_uploadimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimages',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadimages',
            name='first_name',
            field=models.CharField(default=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='uploadimages',
            name='last_name',
            field=models.CharField(default=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadimages',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
