# Generated by Django 3.2.4 on 2022-11-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20221121_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImages',
        ),
    ]
