# Generated by Django 3.2.4 on 2022-12-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_messagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='phone',
            field=models.IntegerField(max_length=200),
        ),
    ]
