# Generated by Django 3.2.4 on 2022-12-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_alter_messagemodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
