# Generated by Django 3.2.4 on 2022-12-02 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_alter_messagemodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='phone',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
