# Generated by Django 3.2.4 on 2022-12-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0024_messagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
