# Generated by Django 3.2.4 on 2022-12-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0025_auto_20221206_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='000000000', max_length=50, null=True),
        ),
    ]
