# Generated by Django 3.2.4 on 2022-12-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0027_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
