# Generated by Django 3.2.4 on 2022-12-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fisrt_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile', models.CharField(default='1234567890', max_length=100)),
            ],
        ),
    ]
