# Generated by Django 3.2.4 on 2022-12-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_with_otp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
