# Generated by Django 3.2.4 on 2022-12-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_with_otp', '0002_rename_fisrt_name_profile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
